### ISSUE TITLE
Large-scale 3D Point Generation?

### ISSUE THREAD

**Issue by thomhert** [prajwalsingh/TreeGCN-GAN#1]
Hi!
Thank you for sharing your works.
Wondering if the codes can be used to generate large-scale 3d points i.e 50k? Thank you.

**Comment by prajwalsingh** [comment]
Hi,
[It's an unofficial implementation.]

I have never tried generating shapes of that size, but I think it can generate. Mostly the power of 2 (32768 or 65536) will take more time to train.
