### ISSUE TITLE
About the Generator

### ISSUE THREAD

**Issue by MarkLiSS** [prajwalsingh/TreeGCN-GAN#2]
Thank you for your code! But I am wondering how can i get the pointcloud of a certain class if the generator was trained over all the classes?

**Comment by prajwalsingh** [comment]
Hi,

For that, you have to train the TreeGAN from scratch with a conditional vector similar to the Condition-GAN paper. You need to make modifications in the input dimension.

Another trick is to generate random 50,000 shapes or more shapes. Now, if you want to get, say, class "Chair," use some ground-truth point cloud data of the chair, calculate the Chamfer Distance between all the generated shapes, and select the top 100 minimum distance shapes that might be close to a chair or other class.
